#!/bin/bash

VERSIONLIST=("390" "455")
PRIORITY=0
DATE=$(date +%Y.%m.%d)

# $1 template path
# $2 output path
# $3 version
# $4 priority
function generateConfigForVersion
{
  [ -n "$4" ] && PRIORITY="$4"
  local CONFLICTS=()
  local CONFLICTS_64=()
  local CONKMOD=()
  # Generate conflicts for version
  for i in "${VERSIONLIST[@]/$3}"
  do
    [ -z "$i" ] && continue
    if [ "$i" == "455" ]; then
        CONFLICTS+=("nvidia-utils")
        CONFLICTS_64+=("lib32-nvidia-utils")
        CONKMOD+=("nvidia")
    else
        CONFLICTS+=("nvidia-${i}xx-utils")
        CONFLICTS_64+=("lib32-nvidia-${i}xx-utils")
        CONKMOD+=("nvidia-${i}xx")
    fi
  done

  CONFLICTS="${CONFLICTS[@]}"
  CONFLICTS_64="${CONFLICTS_64[@]}"
  CONKMOD="${CONKMOD[@]}"

  mkdir "$2"
  sed -e "s/%DATE%/${DATE}/g; s/%VERSION%/${3}/g; s/%PRIORITY%/${PRIORITY}/g; s/%CONFLICTS%/${CONFLICTS}/g; s/%CONFLICTS_64%/${CONFLICTS_64}/g; s/%CONKMOD%/${CONKMOD}/g"  "$1" > "${2}/MHWDCONFIG"
  let "PRIORITY++"
}

# disable nvidia on i686
[ "${CARCH}" = "i686" ] && exit 0

# Stock nvidia drivers
generateConfigForVersion templates/nvidia-xxxxx ./pci/graphic_drivers/nvidia-390xx 390 3
generateConfigForVersion templates/nvidia-xxxxx ./pci/graphic_drivers/nvidia 455 # 4

# Bumblebee
generateConfigForVersion templates/hybrid-intel-nvidia-xxxxx-bumblebee ./pci/graphic_drivers/hybrid-intel-nvidia-390xx-bumblebee 390 5

# Prime intel
generateConfigForVersion templates/hybrid-intel-nvidia-xxxxx-prime ./pci/graphic_drivers/hybrid-intel-nvidia-prime 455 6

# Prime amd
generateConfigForVersion templates/hybrid-amd-nvidia-xxxxx-prime ./pci/graphic_drivers/hybrid-amd-nvidia-prime 455 7
